"""add xiaoyunque_runs

Revision ID: 5811a7ff5456
Revises: 8b1e8a1290ca
Create Date: 2026-05-28 12:38:15.971346

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5811a7ff5456"
down_revision: str | Sequence[str] | None = "8b1e8a1290ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "xiaoyunque_runs" in inspector.get_table_names():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "xiaoyunque_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("model_variant", sa.String(), server_default="fast720p", nullable=False),
        sa.Column("visual_style", sa.String(), nullable=False),
        sa.Column("video_ratio", sa.String(), server_default="16:9", nullable=False),
        sa.Column("thread_id", sa.String(), nullable=True),
        sa.Column("assets_id", sa.String(), nullable=True),
        sa.Column("script_file_url", sa.Text(), nullable=False),
        sa.Column("state_json", sa.Text(), server_default="{}", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.String(), server_default="default", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("xiaoyunque_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_xiaoyunque_runs_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("xiaoyunque_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_xiaoyunque_runs_user_id"))

    op.drop_table("xiaoyunque_runs")
    # ### end Alembic commands ###
